modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[mods.config]]
type="forge"
file="lestora-biome.toml"

[[dependencies.lestora_debug]]
modId="lestora_debug"
mandatory=true
versionRange="[1.0.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.lestora_block_support]]
modId="lestora_block_support"
mandatory=true
versionRange="[1.0.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.lestora_wetness]]
modId="lestora_wetness"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"